### ISSUE TITLE
Fails to Build in Centos 6.3

### ISSUE THREAD

**Issue by uxdiogenes** [jeremycx/node-LDAP#30]
Error looks like this:

```
[root@meteor cyberoffice]# npm install LDAP
npm http GET https://registry.npmjs.org/LDAP
npm http 304 https://registry.npmjs.org/LDAP

> LDAP@1.1.4 install /tmp/cyberoffice/node_modules/LDAP
> node-gyp rebuild

make: Entering directory `/tmp/cyberoffice/node_modules/LDAP/build'
  CXX(target) Release/obj.target/LDAP/src/LDAP.o
../src/LDAP.cc: In static member function ‘static v8::Handle<v8::Value> LDAPConnection::Open(const v8::Arguments&)’:
../src/LDAP.cc:230: warning: unused variable ‘timelimit’
../src/LDAP.cc:231: warning: unused variable ‘sizelimit’
../src/LDAP.cc: In static member function ‘static void LDAPConnection::io_event(uv_poll_t*, int, int)’:
../src/LDAP.cc:796: error: ‘EV_READ’ was not declared in this scope
make: *** [Release/obj.target/LDAP/src/LDAP.o] Error 1
make: Leaving directory `/tmp/cyberoffice/node_modules/LDAP/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:784:12)
gyp ERR! System Linux 2.6.32-279.19.1.el6.x86_64
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/cyberoffice/node_modules/LDAP
gyp ERR! node -v v0.10.5
gyp ERR! node-gyp -v v0.9.5
gyp ERR! not ok 
npm ERR! LDAP@1.1.4 install: `node-gyp rebuild`
npm ERR! `sh "-c" "node-gyp rebuild"` failed with 1
npm ERR! 
npm ERR! Failed at the LDAP@1.1.4 install script.
npm ERR! This is most likely a problem with the LDAP package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls LDAP
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 2.6.32-279.19.1.el6.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "LDAP"
npm ERR! cwd /tmp/cyberoffice
npm ERR! node -v v0.10.5
npm ERR! npm -v 1.2.18
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /tmp/cyberoffice/npm-debug.log
npm ERR! not ok code 0
```
